interface ISO27001Control {
  id: string
  title: string
  description: string
  category: string
  domain: string
  objective: string
  implementationGuidance: string
  typicalEvidence: string[]
  relatedControls: string[]
  mandatory: boolean
}

const iso27001AnnexAControls: ISO27001Control[] = [
  // A.5 Organizational Controls
  {
    id: 'A.5.1',
    title: 'Policies for information security',
    description: 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Establish clear information security governance and policy framework',
    implementationGuidance: 'Develop comprehensive information security policies covering all aspects of information security management. Ensure policies are approved by senior management, communicated to all personnel, and regularly reviewed.',
    typicalEvidence: ['Information security policy document', 'Policy approval records', 'Communication and training records'],
    relatedControls: ['A.5.2', 'A.5.4', 'A.5.35'],
    mandatory: true
  },
  {
    id: 'A.5.2',
    title: 'Information Security Roles and Responsibilities',
    description: 'Information security roles and responsibilities shall be defined and allocated in accordance with the organization needs.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure clear accountability for information security activities',
    implementationGuidance: 'Define and document roles and responsibilities for information security throughout the organization. Assign specific security responsibilities to individuals and teams.',
    typicalEvidence: ['Role and responsibility matrix', 'Job descriptions with security responsibilities', 'RACI matrix'],
    relatedControls: ['A.5.1', 'A.5.4', 'A.6.2'],
    mandatory: true
  },
  {
    id: 'A.5.3',
    title: 'Segregation of duties',
    description: 'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization assets.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Prevent conflicts of interest and reduce risk of errors or fraud',
    implementationGuidance: 'Implement segregation of duties to prevent conflicts of interest and reduce risk of errors or fraud. Identify and separate conflicting duties across different roles.',
    typicalEvidence: ['Segregation of duties matrix', 'Process documentation', 'Access control records'],
    relatedControls: ['A.5.15', 'A.5.18', 'A.8.2'],
    mandatory: false
  },
  {
    id: 'A.5.4',
    title: 'Management responsibilities',
    description: 'Management shall require all personnel to apply information security in accordance with the established policies and procedures of the organization.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure management commitment and accountability for information security',
    implementationGuidance: 'Establish management oversight and accountability for information security implementation. Demonstrate leadership commitment through active participation and resource allocation.',
    typicalEvidence: ['Management directives', 'Security committee minutes', 'Resource allocation records'],
    relatedControls: ['A.5.1', 'A.5.2', 'A.6.3'],
    mandatory: true
  },
  {
    id: 'A.5.5',
    title: 'Contact with authorities',
    description: 'Appropriate contacts with relevant authorities shall be maintained.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Maintain relationships with law enforcement and regulatory authorities',
    implementationGuidance: 'Establish and maintain relationships with law enforcement, regulators, and other relevant authorities. Document contact procedures for incident reporting.',
    typicalEvidence: ['Contact list of authorities', 'Communication procedures', 'Incident reporting records'],
    relatedControls: ['A.5.6', 'A.5.24', 'A.5.26'],
    mandatory: false
  },
  {
    id: 'A.5.6',
    title: 'Contact with special interest groups',
    description: 'Appropriate contacts with special interest groups or other specialist security forums and professional associations shall be maintained.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Stay informed of security developments and best practices',
    implementationGuidance: 'Participate in security communities and maintain awareness of emerging threats and best practices. Join relevant professional associations and forums.',
    typicalEvidence: ['Membership records', 'Forum participation evidence', 'Threat intelligence feeds'],
    relatedControls: ['A.5.5', 'A.5.7', 'A.5.35'],
    mandatory: false
  },
  {
    id: 'A.5.7',
    title: 'Threat intelligence',
    description: 'Information relating to information security threats shall be collected and analysed to produce threat intelligence.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Maintain awareness of current and emerging security threats',
    implementationGuidance: 'Implement threat intelligence gathering and analysis capabilities to stay informed of current threats. Subscribe to threat feeds and security bulletins.',
    typicalEvidence: ['Threat intelligence reports', 'Threat feed subscriptions', 'Analysis documentation'],
    relatedControls: ['A.5.6', 'A.5.24', 'A.8.8'],
    mandatory: false
  },
  {
    id: 'A.5.8',
    title: 'Information security in project management',
    description: 'Information security shall be integrated into project management.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure security considerations are included in all projects',
    implementationGuidance: 'Integrate security considerations into all project management processes and methodologies. Include security requirements in project planning and execution.',
    typicalEvidence: ['Project security requirements', 'Security review checkpoints', 'Project documentation'],
    relatedControls: ['A.8.26', 'A.8.27', 'A.8.32'],
    mandatory: false
  },
  {
    id: 'A.5.9',
    title: 'Inventory of information and other associated assets',
    description: 'An inventory of information and other associated assets, including owners, shall be developed and maintained.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Maintain comprehensive visibility of organizational assets',
    implementationGuidance: 'Maintain a comprehensive inventory of all information assets and assign clear ownership. Include hardware, software, data, and personnel assets.',
    typicalEvidence: ['Asset inventory database', 'Asset ownership records', 'Asset classification records'],
    relatedControls: ['A.5.12', 'A.7.14', 'A.8.10'],
    mandatory: true
  },
  {
    id: 'A.5.10',
    title: 'Acceptable use of information and other associated assets',
    description: 'Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Define appropriate use of organizational assets',
    implementationGuidance: 'Develop and communicate acceptable use policies for all organizational assets. Include guidelines for appropriate business use and prohibited activities.',
    typicalEvidence: ['Acceptable use policy', 'User acknowledgments', 'Monitoring records'],
    relatedControls: ['A.5.12', 'A.6.2', 'A.6.6'],
    mandatory: false
  },
  {
    id: 'A.5.11',
    title: 'Return of assets',
    description: 'All employees and external party users shall return all of the organizational assets in their possession upon termination of their employment, contract or agreement.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure complete recovery of organizational assets upon termination',
    implementationGuidance: 'Establish procedures for asset return during employment termination or contract completion. Include physical and logical assets.',
    typicalEvidence: ['Asset return procedures', 'Return checklists', 'Termination records'],
    relatedControls: ['A.6.5', 'A.5.18', 'A.8.1'],
    mandatory: false
  },
  {
    id: 'A.5.12',
    title: 'Classification of information',
    description: 'Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure appropriate protection based on information value and sensitivity',
    implementationGuidance: 'Implement an information classification scheme and ensure proper labeling and handling. Base classification on confidentiality, integrity, and availability requirements.',
    typicalEvidence: ['Information classification scheme', 'Classified information inventory', 'Classification guidelines'],
    relatedControls: ['A.5.13', 'A.5.14', 'A.8.24'],
    mandatory: true
  },
  {
    id: 'A.5.13',
    title: 'Labelling of information',
    description: 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure proper identification and handling of classified information',
    implementationGuidance: 'Develop and implement information labeling procedures consistent with classification scheme. Include both physical and electronic labeling methods.',
    typicalEvidence: ['Labeling procedures', 'Labeled documents/systems', 'Training records'],
    relatedControls: ['A.5.12', 'A.5.14', 'A.7.10'],
    mandatory: false
  },
  {
    id: 'A.5.14',
    title: 'Information transfer',
    description: 'Information transfer rules, procedures or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Protect information during transmission and sharing',
    implementationGuidance: 'Establish secure information transfer procedures including email security and file sharing controls. Implement encryption for sensitive data in transit.',
    typicalEvidence: ['Information transfer procedures', 'Transfer agreements', 'Encryption standards'],
    relatedControls: ['A.5.12', 'A.8.24', 'A.8.20'],
    mandatory: false
  },
  {
    id: 'A.5.15',
    title: 'Access control',
    description: 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure only authorized access to information and assets',
    implementationGuidance: 'Establish access control policies and procedures based on business requirements. Include both physical and logical access controls.',
    typicalEvidence: ['Access control policy', 'Access procedures', 'Access control matrix'],
    relatedControls: ['A.5.16', 'A.5.18', 'A.8.2'],
    mandatory: true
  },
  {
    id: 'A.5.16',
    title: 'Identity management',
    description: 'The full life cycle of identities shall be managed.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Manage user identities throughout their complete lifecycle',
    implementationGuidance: 'Implement identity lifecycle management from creation to deletion. Include procedures for identity provisioning, modification, and deprovisioning.',
    typicalEvidence: ['Identity management procedures', 'Identity lifecycle records', 'Identity management system'],
    relatedControls: ['A.5.17', 'A.5.18', 'A.8.5'],
    mandatory: false
  },
  {
    id: 'A.5.17',
    title: 'Authentication information',
    description: 'Allocation and management of authentication information shall be controlled by a management process.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Ensure secure management of authentication credentials',
    implementationGuidance: 'Implement secure management of authentication credentials and tokens. Include password policies, secure distribution, and regular updates.',
    typicalEvidence: ['Authentication procedures', 'Password policies', 'Credential management records'],
    relatedControls: ['A.5.16', 'A.8.5', 'A.8.2'],
    mandatory: false
  },
  {
    id: 'A.5.18',
    title: 'Access rights',
    description: 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization topic-specific policy on access control.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Maintain appropriate access rights throughout user lifecycle',
    implementationGuidance: 'Implement access rights management with regular reviews and updates. Include procedures for granting, modifying, and revoking access.',
    typicalEvidence: ['Access rights procedures', 'Access review records', 'Access provisioning logs'],
    relatedControls: ['A.5.15', 'A.5.16', 'A.8.3'],
    mandatory: true
  },
  {
    id: 'A.5.19',
    title: 'Information security in supplier relationships',
    description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier products or services.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Manage security risks in supplier relationships',
    implementationGuidance: 'Establish security requirements and controls for supplier relationships. Include risk assessment and ongoing monitoring of suppliers.',
    typicalEvidence: ['Supplier security procedures', 'Supplier assessments', 'Security requirements documentation'],
    relatedControls: ['A.5.20', 'A.5.21', 'A.5.22'],
    mandatory: false
  },
  {
    id: 'A.5.20',
    title: 'Addressing information security within supplier agreements',
    description: 'Relevant information security requirements shall be established and agreed with each supplier that may access, process, store, communicate, or provide IT infrastructure components for, the organization information.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure contractual security obligations with suppliers',
    implementationGuidance: 'Include comprehensive security requirements in all supplier contracts and agreements. Address data protection, incident notification, and audit rights.',
    typicalEvidence: ['Supplier contracts with security clauses', 'Security requirements templates', 'Contract review records'],
    relatedControls: ['A.5.19', 'A.5.21', 'A.5.34'],
    mandatory: false
  },
  {
    id: 'A.5.21',
    title: 'Managing information security in the ICT supply chain',
    description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Secure the ICT supply chain against security risks',
    implementationGuidance: 'Implement supply chain security management for ICT products and services. Include security validation and ongoing monitoring.',
    typicalEvidence: ['Supply chain security procedures', 'Vendor security assessments', 'Product security certifications'],
    relatedControls: ['A.5.19', 'A.5.20', 'A.8.30'],
    mandatory: false
  },
  {
    id: 'A.5.22',
    title: 'Monitoring, review and change management of supplier services',
    description: 'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure ongoing security of supplier services',
    implementationGuidance: 'Establish ongoing monitoring and review processes for supplier security performance. Include change management procedures for supplier modifications.',
    typicalEvidence: ['Supplier monitoring reports', 'Security performance reviews', 'Change management records'],
    relatedControls: ['A.5.19', 'A.5.21', 'A.8.32'],
    mandatory: false
  },
  {
    id: 'A.5.23',
    title: 'Information security for use of cloud services',
    description: 'Processes for the acquisition, use, management and exit from cloud services shall be established in accordance with the organization information security requirements.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Manage security risks associated with cloud services',
    implementationGuidance: 'Develop cloud security governance including assessment, monitoring, and exit procedures. Address data location, encryption, and compliance requirements.',
    typicalEvidence: ['Cloud security procedures', 'Cloud service assessments', 'Data migration plans'],
    relatedControls: ['A.5.19', 'A.5.34', 'A.8.24'],
    mandatory: false
  },
  {
    id: 'A.5.24',
    title: 'Information security incident management planning and preparation',
    description: 'The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Establish capability to respond effectively to security incidents',
    implementationGuidance: 'Establish incident response procedures including detection, reporting, assessment, and recovery. Define roles and responsibilities for incident response team.',
    typicalEvidence: ['Incident response plan', 'Incident response procedures', 'Team training records'],
    relatedControls: ['A.5.25', 'A.5.26', 'A.6.8'],
    mandatory: true
  },
  {
    id: 'A.5.25',
    title: 'Assessment and decision on information security events',
    description: 'The organization shall assess information security events and decide if they are to be categorized as information security incidents.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Properly classify and prioritize security events',
    implementationGuidance: 'Implement event assessment and incident classification procedures. Define criteria for escalating events to incidents.',
    typicalEvidence: ['Event assessment procedures', 'Classification criteria', 'Event logs and decisions'],
    relatedControls: ['A.5.24', 'A.5.26', 'A.8.16'],
    mandatory: false
  },
  {
    id: 'A.5.26',
    title: 'Response to information security incidents',
    description: 'Information security incidents shall be responded to in accordance with the documented procedures.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure effective and timely response to security incidents',
    implementationGuidance: 'Develop and implement structured incident response procedures. Include containment, eradication, recovery, and lessons learned phases.',
    typicalEvidence: ['Incident response procedures', 'Incident records', 'Response time metrics'],
    relatedControls: ['A.5.24', 'A.5.27', 'A.5.28'],
    mandatory: true
  },
  {
    id: 'A.5.27',
    title: 'Learning from information security incidents',
    description: 'Knowledge gained from analysing and resolving information security incidents shall be used to strengthen and improve the information security controls.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Continuously improve security based on incident experience',
    implementationGuidance: 'Implement lessons learned processes to improve security controls based on incidents. Conduct post-incident reviews and implement improvements.',
    typicalEvidence: ['Post-incident reviews', 'Lessons learned documentation', 'Control improvement records'],
    relatedControls: ['A.5.26', 'A.5.35', 'A.8.8'],
    mandatory: false
  },
  {
    id: 'A.5.28',
    title: 'Collection of evidence',
    description: 'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of information that can serve as evidence.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure proper collection and preservation of forensic evidence',
    implementationGuidance: 'Establish forensic evidence collection and preservation procedures. Include chain of custody and legal admissibility requirements.',
    typicalEvidence: ['Forensic procedures', 'Evidence handling records', 'Chain of custody documentation'],
    relatedControls: ['A.5.26', 'A.8.15', 'A.8.17'],
    mandatory: false
  },
  {
    id: 'A.5.29',
    title: 'Information security during disruption',
    description: 'The organization shall plan how to maintain information security at an appropriate level during disruption.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Maintain security during business disruption',
    implementationGuidance: 'Integrate information security requirements into business continuity planning. Ensure security controls remain effective during disruptions.',
    typicalEvidence: ['Business continuity plans with security components', 'Continuity testing records', 'Security procedures for disruption'],
    relatedControls: ['A.5.30', 'A.7.11', 'A.8.14'],
    mandatory: false
  },
  {
    id: 'A.5.30',
    title: 'ICT readiness for business continuity',
    description: 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.',
    category: 'Organizational Controls',
    domain: 'Technology',
    objective: 'Ensure ICT systems support business continuity requirements',
    implementationGuidance: 'Implement redundant systems and infrastructure to ensure business continuity. Include backup systems, data replication, and disaster recovery procedures.',
    typicalEvidence: ['ICT continuity plans', 'Redundancy documentation', 'Continuity testing results'],
    relatedControls: ['A.5.29', 'A.8.13', 'A.8.14'],
    mandatory: false
  },
  {
    id: 'A.5.31',
    title: 'Identification of legal, statutory, regulatory and contractual requirements',
    description: 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organization approach to meet these requirements shall be identified, documented and kept up to date.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure compliance with all applicable legal and regulatory requirements',
    implementationGuidance: 'Establish compliance management processes to ensure adherence to legal and regulatory requirements. Maintain a current register of applicable requirements.',
    typicalEvidence: ['Compliance register', 'Legal requirement analysis', 'Compliance procedures'],
    relatedControls: ['A.5.32', 'A.5.34', 'A.5.36'],
    mandatory: true
  },
  {
    id: 'A.5.32',
    title: 'Intellectual property rights',
    description: 'The organization shall implement appropriate procedures to protect intellectual property rights.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Protect organizational and third-party intellectual property',
    implementationGuidance: 'Establish procedures to protect and manage intellectual property rights. Include software licensing, trademark protection, and patent management.',
    typicalEvidence: ['IP protection procedures', 'Software license inventory', 'IP usage agreements'],
    relatedControls: ['A.5.31', 'A.5.33', 'A.6.6'],
    mandatory: false
  },
  {
    id: 'A.5.33',
    title: 'Protection of records',
    description: 'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure integrity and availability of important records',
    implementationGuidance: 'Implement records protection and retention procedures. Include backup, access controls, and secure disposal of records.',
    typicalEvidence: ['Records management procedures', 'Records inventory', 'Retention schedules'],
    relatedControls: ['A.5.31', 'A.8.10', 'A.8.13'],
    mandatory: false
  },
  {
    id: 'A.5.34',
    title: 'Privacy and protection of PII',
    description: 'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Protect personal information and ensure privacy compliance',
    implementationGuidance: 'Implement privacy protection measures and PII handling procedures. Include data subject rights, consent management, and breach notification.',
    typicalEvidence: ['Privacy policy', 'PII handling procedures', 'Data protection impact assessments'],
    relatedControls: ['A.5.31', 'A.8.11', 'A.8.12'],
    mandatory: false
  },
  {
    id: 'A.5.35',
    title: 'Independent review of information security',
    description: 'The organization approach to managing information security and its implementation shall be reviewed independently at planned intervals or when significant changes occur.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure objective assessment of security management effectiveness',
    implementationGuidance: 'Conduct regular independent security reviews and assessments. Include internal audits, external assessments, and management reviews.',
    typicalEvidence: ['Independent review reports', 'Audit schedules', 'Assessment findings'],
    relatedControls: ['A.5.36', 'A.5.1', 'A.5.27'],
    mandatory: false
  },
  {
    id: 'A.5.36',
    title: 'Compliance with policies and standards for information security',
    description: 'Compliance with the organization information security policy, topic-specific policies, procedures and information security controls shall be regularly reviewed.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure ongoing compliance with security policies and procedures',
    implementationGuidance: 'Implement regular compliance monitoring and review processes. Include automated monitoring tools and periodic compliance assessments.',
    typicalEvidence: ['Compliance monitoring reports', 'Policy compliance assessments', 'Non-compliance registers'],
    relatedControls: ['A.5.35', 'A.5.31', 'A.5.1'],
    mandatory: false
  },
  {
    id: 'A.5.37',
    title: 'Documented operating procedures',
    description: 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.',
    category: 'Organizational Controls',
    domain: 'Organizational',
    objective: 'Ensure consistent and secure operation of information systems',
    implementationGuidance: 'Document and maintain operating procedures for all critical systems and processes. Ensure procedures are accessible to authorized personnel.',
    typicalEvidence: ['Operating procedures documentation', 'Procedure distribution records', 'Procedure update logs'],
    relatedControls: ['A.8.32', 'A.7.13', 'A.8.6'],
    mandatory: false
  },

  // A.6 People Controls
  {
    id: 'A.6.1',
    title: 'Screening',
    description: 'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Reduce risks associated with human resources through appropriate screening',
    implementationGuidance: 'Implement background screening procedures for all personnel with access to sensitive information. Include criminal background checks, reference verification, and qualification validation.',
    typicalEvidence: ['Screening procedures', 'Background check records', 'Risk-based screening matrix'],
    relatedControls: ['A.6.2', 'A.5.18', 'A.5.15'],
    mandatory: false
  },
  {
    id: 'A.6.2',
    title: 'Terms and conditions of employment',
    description: 'The terms and conditions of employment shall address the personnel and the organization responsibilities for information security.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Establish clear security responsibilities for personnel',
    implementationGuidance: 'Include information security responsibilities in employment contracts and agreements. Define consequences for security violations and ongoing obligations.',
    typicalEvidence: ['Employment contracts with security clauses', 'Security responsibility agreements', 'Terms and conditions documentation'],
    relatedControls: ['A.6.1', 'A.6.6', 'A.5.10'],
    mandatory: false
  },
  {
    id: 'A.6.3',
    title: 'Information security awareness, education and training',
    description: 'Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization information security policy, topic-specific policies and procedures.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Ensure personnel understand their security responsibilities',
    implementationGuidance: 'Implement comprehensive security awareness and training programs. Include regular updates, role-specific training, and ongoing awareness activities.',
    typicalEvidence: ['Training programs', 'Training records', 'Awareness materials'],
    relatedControls: ['A.5.1', 'A.6.2', 'A.8.7'],
    mandatory: true
  },
  {
    id: 'A.6.4',
    title: 'Disciplinary process',
    description: 'A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Deter security violations through clear consequences',
    implementationGuidance: 'Establish formal disciplinary procedures that are communicated to all employees. Include graduated responses and ensure consistent application.',
    typicalEvidence: ['Disciplinary procedures', 'Communication records', 'Disciplinary action records'],
    relatedControls: ['A.6.2', 'A.5.1', 'A.6.5'],
    mandatory: false
  },
  {
    id: 'A.6.5',
    title: 'Responsibilities after termination or change of employment',
    description: 'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Ensure security obligations continue after employment ends',
    implementationGuidance: 'Define post-employment security responsibilities and ensure proper handover procedures. Include ongoing confidentiality and non-disclosure obligations.',
    typicalEvidence: ['Post-employment obligations', 'Termination procedures', 'Confidentiality agreements'],
    relatedControls: ['A.5.11', 'A.6.6', 'A.5.18'],
    mandatory: false
  },
  {
    id: 'A.6.6',
    title: 'Confidentiality or non-disclosure agreements',
    description: 'Confidentiality or non-disclosure agreements reflecting the organization needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Protect confidential information through legal agreements',
    implementationGuidance: 'Implement comprehensive confidentiality and non-disclosure agreements. Include employees, contractors, and third parties with access to sensitive information.',
    typicalEvidence: ['NDA templates', 'Signed agreements', 'Agreement tracking records'],
    relatedControls: ['A.6.2', 'A.6.5', 'A.5.32'],
    mandatory: false
  },
  {
    id: 'A.6.7',
    title: 'Remote working',
    description: 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization premises.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Maintain security for remote work arrangements',
    implementationGuidance: 'Implement security controls for remote work including secure connections and endpoint protection. Address physical security and information handling requirements.',
    typicalEvidence: ['Remote work policies', 'VPN configurations', 'Endpoint security controls'],
    relatedControls: ['A.8.1', 'A.8.20', 'A.7.9'],
    mandatory: false
  },
  {
    id: 'A.6.8',
    title: 'Information security event reporting',
    description: 'The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.',
    category: 'People Controls',
    domain: 'People',
    objective: 'Enable early detection and reporting of security events',
    implementationGuidance: 'Establish clear incident reporting procedures and communication channels. Provide multiple reporting methods and protect reporters from retaliation.',
    typicalEvidence: ['Incident reporting procedures', 'Reporting channels', 'Event reporting records'],
    relatedControls: ['A.5.24', 'A.5.25', 'A.6.3'],
    mandatory: false
  },

  // A.7 Physical Controls
  {
    id: 'A.7.1',
    title: 'Physical security perimeter',
    description: 'Physical security perimeters shall be defined and used to protect areas that contain information and other associated assets.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Prevent unauthorized physical access to sensitive areas',
    implementationGuidance: 'Establish and maintain physical security perimeters around sensitive areas. Include barriers, access control points, and monitoring systems.',
    typicalEvidence: ['Physical security designs', 'Perimeter access logs', 'Security barrier documentation'],
    relatedControls: ['A.7.2', 'A.7.4', 'A.7.3'],
    mandatory: false
  },
  {
    id: 'A.7.2',
    title: 'Physical entry controls',
    description: 'Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Control and monitor physical access to secure areas',
    implementationGuidance: 'Implement access control systems for physical entry to sensitive areas. Include card readers, biometric systems, and visitor management.',
    typicalEvidence: ['Access control systems', 'Access logs', 'Visitor management records'],
    relatedControls: ['A.7.1', 'A.7.6', 'A.5.15'],
    mandatory: false
  },
  {
    id: 'A.7.3',
    title: 'Securing offices, rooms and facilities',
    description: 'Physical security for offices, rooms and facilities shall be designed and implemented.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Protect physical work environments from security threats',
    implementationGuidance: 'Design and implement appropriate physical security measures for work areas. Include locks, security glass, and environmental controls.',
    typicalEvidence: ['Physical security assessments', 'Security design documentation', 'Physical control inventories'],
    relatedControls: ['A.7.1', 'A.7.5', 'A.7.8'],
    mandatory: false
  },
  {
    id: 'A.7.4',
    title: 'Physical security monitoring',
    description: 'Premises shall be continuously monitored for unauthorized physical access.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Detect and respond to unauthorized physical access attempts',
    implementationGuidance: 'Implement continuous physical security monitoring systems. Include CCTV, motion detectors, and alarm systems with appropriate response procedures.',
    typicalEvidence: ['Monitoring system documentation', 'Surveillance logs', 'Alarm response procedures'],
    relatedControls: ['A.7.1', 'A.7.2', 'A.5.25'],
    mandatory: false
  },
  {
    id: 'A.7.5',
    title: 'Protecting against physical and environmental threats',
    description: 'Protection against physical and environmental threats shall be designed and implemented.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Protect facilities and equipment from environmental damage',
    implementationGuidance: 'Implement protection against environmental threats like fire, flood, and power failure. Include fire suppression, flood protection, and UPS systems.',
    typicalEvidence: ['Environmental protection systems', 'Risk assessments', 'Emergency procedures'],
    relatedControls: ['A.7.11', 'A.5.29', 'A.8.14'],
    mandatory: false
  },
  {
    id: 'A.7.6',
    title: 'Working in secure areas',
    description: 'Security measures for working in secure areas shall be designed and implemented.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Maintain security when working in protected areas',
    implementationGuidance: 'Establish procedures and controls for personnel working in secure areas. Include escort requirements, work restrictions, and security briefings.',
    typicalEvidence: ['Secure area procedures', 'Access authorization records', 'Security briefing records'],
    relatedControls: ['A.7.2', 'A.7.7', 'A.6.3'],
    mandatory: false
  },
  {
    id: 'A.7.7',
    title: 'Clear desk and clear screen',
    description: 'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Prevent unauthorized access to information in work areas',
    implementationGuidance: 'Implement and enforce clear desk and clear screen policies. Include automatic screen locks and secure storage requirements.',
    typicalEvidence: ['Clear desk policies', 'Compliance monitoring records', 'Automatic screen lock configurations'],
    relatedControls: ['A.7.6', 'A.7.10', 'A.5.10'],
    mandatory: false
  },
  {
    id: 'A.7.8',
    title: 'Equipment siting and protection',
    description: 'Equipment shall be sited securely and protected.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Protect equipment from physical damage and unauthorized access',
    implementationGuidance: 'Ensure secure placement and protection of all equipment. Include environmental controls, physical locks, and cable protection.',
    typicalEvidence: ['Equipment placement guidelines', 'Physical protection measures', 'Environmental monitoring'],
    relatedControls: ['A.7.3', 'A.7.12', 'A.7.5'],
    mandatory: false
  },
  {
    id: 'A.7.9',
    title: 'Security of assets off-premises',
    description: 'Off-site assets shall be protected.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Maintain security for assets used outside organizational premises',
    implementationGuidance: 'Implement security controls for assets used outside organizational premises. Include mobile devices, portable storage, and documents.',
    typicalEvidence: ['Off-site asset procedures', 'Mobile device management policies', 'Asset tracking records'],
    relatedControls: ['A.8.1', 'A.6.7', 'A.5.11'],
    mandatory: false
  },
  {
    id: 'A.7.10',
    title: 'Storage media',
    description: 'Storage media shall be managed in accordance with the classification scheme adopted by the organization.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Protect storage media based on information classification',
    implementationGuidance: 'Implement secure storage media handling and disposal procedures. Include labeling, secure storage, and sanitization before disposal.',
    typicalEvidence: ['Media handling procedures', 'Disposal records', 'Storage media inventory'],
    relatedControls: ['A.5.12', 'A.7.14', 'A.8.10'],
    mandatory: false
  },
  {
    id: 'A.7.11',
    title: 'Supporting Utilities',
    description: 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Ensure continuity of power and supporting utilities',
    implementationGuidance: 'Implement redundant utilities and backup power systems. Include UPS systems, generators, and multiple utility feeds.',
    typicalEvidence: ['Utility redundancy documentation', 'UPS test records', 'Generator maintenance logs'],
    relatedControls: ['A.7.5', 'A.5.30', 'A.8.14'],
    mandatory: false
  },
  {
    id: 'A.7.12',
    title: 'Cabling Security',
    description: 'Power and telecommunications cabling carrying data or supporting information services shall be protected from interception, interference or damage.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Protect data transmission cables from threats',
    implementationGuidance: 'Implement physical protection for data and power cabling. Include conduits, cable trays, and protection from electromagnetic interference.',
    typicalEvidence: ['Cable protection designs', 'Installation documentation', 'EMI protection measures'],
    relatedControls: ['A.7.8', 'A.8.20', 'A.7.3'],
    mandatory: false
  },
  {
    id: 'A.7.13',
    title: 'Equipment Maintenance',
    description: 'Equipment shall be correctly maintained to ensure availability, integrity and confidentiality of information.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Maintain equipment security through proper maintenance',
    implementationGuidance: 'Establish equipment maintenance procedures that preserve security. Include authorized service providers and sanitization requirements.',
    typicalEvidence: ['Maintenance procedures', 'Service provider agreements', 'Maintenance records'],
    relatedControls: ['A.5.19', 'A.7.8', 'A.8.6'],
    mandatory: false
  },
  {
    id: 'A.7.14',
    title: 'Secure Disposal or Re-Use of Equipment',
    description: 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.',
    category: 'Physical Controls',
    domain: 'Physical',
    objective: 'Prevent data leakage through equipment disposal or reuse',
    implementationGuidance: 'Implement secure data sanitization and equipment disposal procedures. Include data wiping, physical destruction, and disposal certificates.',
    typicalEvidence: ['Disposal procedures', 'Data sanitization records', 'Disposal certificates'],
    relatedControls: ['A.8.10', 'A.7.10', 'A.5.9'],
    mandatory: false
  },

  // A.8 Technology Controls
  {
    id: 'A.8.1',
    title: 'User Endpoint Devices',
    description: 'Information stored on, processed by or accessible via user endpoint devices shall be protected.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Secure endpoint devices used to access organizational information',
    implementationGuidance: 'Implement endpoint protection controls for all user devices. Include anti-malware, encryption, remote wipe capabilities, and device management.',
    typicalEvidence: ['Endpoint protection policies', 'Device management systems', 'Encryption deployment records'],
    relatedControls: ['A.8.7', 'A.6.7', 'A.7.9'],
    mandatory: false
  },
  {
    id: 'A.8.2',
    title: 'Privileged Access Rights',
    description: 'The allocation and use of privileged access rights shall be restricted and managed.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Control and monitor administrative and privileged access',
    implementationGuidance: 'Implement strict controls on administrative and privileged access rights. Include just-in-time access, privileged account management, and monitoring.',
    typicalEvidence: ['Privileged access procedures', 'Privileged account inventory', 'Access monitoring logs'],
    relatedControls: ['A.5.18', 'A.8.5', 'A.8.18'],
    mandatory: true
  },
  {
    id: 'A.8.3',
    title: 'Information Access Restriction',
    description: 'Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Enforce access controls based on business requirements',
    implementationGuidance: 'Implement information access controls based on business requirements and data classification. Include role-based access control and need-to-know principles.',
    typicalEvidence: ['Access control implementation', 'Access control lists', 'Role definitions'],
    relatedControls: ['A.5.15', 'A.5.18', 'A.5.12'],
    mandatory: false
  },
  {
    id: 'A.8.4',
    title: 'Access To Source Code',
    description: 'Read and write access to source code, development tools and software libraries shall be appropriately managed.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect source code and development resources',
    implementationGuidance: 'Implement controls for source code access and version control. Include repository access controls, code review processes, and change tracking.',
    typicalEvidence: ['Source code access controls', 'Version control systems', 'Code review records'],
    relatedControls: ['A.8.31', 'A.8.32', 'A.5.18'],
    mandatory: false
  },
  {
    id: 'A.8.5',
    title: 'Secure Authentication',
    description: 'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure strong authentication for system access',
    implementationGuidance: 'Implement strong authentication mechanisms including multi-factor authentication. Include password policies, biometrics, and token-based authentication.',
    typicalEvidence: ['Authentication system configuration', 'MFA deployment records', 'Authentication policies'],
    relatedControls: ['A.5.17', 'A.8.2', 'A.5.16'],
    mandatory: false
  },
  {
    id: 'A.8.6',
    title: 'Capacity Management',
    description: 'The use of resources shall be monitored and tuned and projections of future capacity requirements shall be made to ensure the required system performance.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Maintain system availability through capacity planning',
    implementationGuidance: 'Implement capacity planning and resource monitoring to ensure system availability. Include performance monitoring, trend analysis, and capacity forecasting.',
    typicalEvidence: ['Capacity monitoring tools', 'Performance reports', 'Capacity planning documentation'],
    relatedControls: ['A.8.14', 'A.5.37', 'A.8.16'],
    mandatory: false
  },
  {
    id: 'A.8.7',
    title: 'Protection Against Malware',
    description: 'Protection against malware shall be implemented and supported by appropriate user awareness.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Prevent and detect malware infections',
    implementationGuidance: 'Deploy comprehensive anti-malware solutions and maintain user awareness programs. Include real-time scanning, signature updates, and incident response.',
    typicalEvidence: ['Anti-malware systems', 'Malware detection reports', 'User awareness training'],
    relatedControls: ['A.8.1', 'A.6.3', 'A.8.23'],
    mandatory: true
  },
  {
    id: 'A.8.8',
    title: 'Management of Technical Vulnerabilities',
    description: 'Information about technical vulnerabilities of information systems in use shall be obtained, the organization exposure to such vulnerabilities evaluated and appropriate measures taken.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Identify and remediate technical vulnerabilities',
    implementationGuidance: 'Establish vulnerability management processes including scanning, assessment, and patching. Include vulnerability databases, patch testing, and emergency patching.',
    typicalEvidence: ['Vulnerability scanning reports', 'Patch management procedures', 'Vulnerability assessments'],
    relatedControls: ['A.5.7', 'A.8.19', 'A.8.32'],
    mandatory: true
  },
  {
    id: 'A.8.9',
    title: 'Configuration Management',
    description: 'Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Maintain secure and consistent system configurations',
    implementationGuidance: 'Implement configuration management to maintain secure system configurations. Include configuration baselines, change control, and compliance monitoring.',
    typicalEvidence: ['Configuration baselines', 'Configuration management tools', 'Compliance reports'],
    relatedControls: ['A.8.32', 'A.8.8', 'A.5.37'],
    mandatory: false
  },
  {
    id: 'A.8.10',
    title: 'Information Deletion',
    description: 'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure secure deletion of unnecessary information',
    implementationGuidance: 'Implement secure data deletion procedures and retention policies. Include automated deletion, secure wiping, and disposal verification.',
    typicalEvidence: ['Data retention policies', 'Deletion procedures', 'Disposal records'],
    relatedControls: ['A.7.14', 'A.5.33', 'A.7.10'],
    mandatory: false
  },
  {
    id: 'A.8.11',
    title: 'Data Masking',
    description: 'Data masking shall be used in accordance with the organization topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect sensitive data in non-production environments',
    implementationGuidance: 'Implement data masking for non-production environments and testing. Include static and dynamic masking techniques based on data sensitivity.',
    typicalEvidence: ['Data masking procedures', 'Masking tool configurations', 'Test data policies'],
    relatedControls: ['A.5.34', 'A.8.33', 'A.5.12'],
    mandatory: false
  },
  {
    id: 'A.8.12',
    title: 'Data Leakage Prevention',
    description: 'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit information.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Prevent unauthorized disclosure of sensitive information',
    implementationGuidance: 'Implement data loss prevention technologies and procedures. Include content inspection, policy enforcement, and incident response for data leakage.',
    typicalEvidence: ['DLP system configuration', 'Data leakage policies', 'DLP incident reports'],
    relatedControls: ['A.5.14', 'A.8.24', 'A.5.34'],
    mandatory: false
  },
  {
    id: 'A.8.13',
    title: 'Information Backup',
    description: 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure information can be recovered when needed',
    implementationGuidance: 'Implement comprehensive backup and recovery procedures with regular testing. Include automated backups, offsite storage, and recovery testing.',
    typicalEvidence: ['Backup procedures', 'Backup test records', 'Recovery documentation'],
    relatedControls: ['A.5.30', 'A.8.14', 'A.5.33'],
    mandatory: true
  },
  {
    id: 'A.8.14',
    title: 'Redundancy of Information Processing Facilities',
    description: 'Information processing facilities shall be implemented with sufficient redundancy to meet availability requirements.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure high availability through system redundancy',
    implementationGuidance: 'Implement redundant systems and infrastructure to ensure high availability. Include failover mechanisms, load balancing, and disaster recovery.',
    typicalEvidence: ['Redundancy architecture', 'Failover procedures', 'Availability monitoring'],
    relatedControls: ['A.5.30', 'A.8.6', 'A.7.11'],
    mandatory: false
  },
  {
    id: 'A.8.15',
    title: 'Logging',
    description: 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Maintain audit trails for security monitoring and forensics',
    implementationGuidance: 'Implement comprehensive logging and monitoring systems with regular review procedures. Include log generation, storage, protection, and analysis.',
    typicalEvidence: ['Logging configuration', 'Log analysis reports', 'Log retention procedures'],
    relatedControls: ['A.8.16', 'A.5.28', 'A.8.17'],
    mandatory: true
  },
  {
    id: 'A.8.16',
    title: 'Monitoring Activities',
    description: 'Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Detect security incidents through continuous monitoring',
    implementationGuidance: 'Implement monitoring and detection systems for security events and anomalies. Include SIEM systems, intrusion detection, and automated alerting.',
    typicalEvidence: ['Monitoring system configuration', 'Security event reports', 'Incident detection records'],
    relatedControls: ['A.8.15', 'A.5.25', 'A.8.20'],
    mandatory: false
  },
  {
    id: 'A.8.17',
    title: 'Clock Synchronisation',
    description: 'The clocks of information processing systems used by the organization shall be synchronized to approved time sources.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure accurate timestamps for logging and forensics',
    implementationGuidance: 'Implement clock synchronization across all systems for accurate logging and forensics. Use NTP servers and maintain time accuracy within acceptable limits.',
    typicalEvidence: ['NTP configuration', 'Time synchronization monitoring', 'Clock accuracy reports'],
    relatedControls: ['A.8.15', 'A.5.28', 'A.8.16'],
    mandatory: false
  },
  {
    id: 'A.8.18',
    title: 'Use of Privileged Utility Programs',
    description: 'The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Control access to powerful administrative tools',
    implementationGuidance: 'Implement strict controls on administrative and privileged access tools. Include approval processes, monitoring, and audit trails for utility usage.',
    typicalEvidence: ['Utility program access controls', 'Usage approval records', 'Utility usage logs'],
    relatedControls: ['A.8.2', 'A.8.15', 'A.5.18'],
    mandatory: false
  },
  {
    id: 'A.8.19',
    title: 'Installation of Software on Operational Systems',
    description: 'Procedures shall be implemented to control the installation of software on operational systems.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Prevent unauthorized software installation and changes',
    implementationGuidance: 'Implement software installation controls and change management procedures. Include approval processes, testing requirements, and rollback procedures.',
    typicalEvidence: ['Software installation procedures', 'Installation approval records', 'Software inventory'],
    relatedControls: ['A.8.32', 'A.8.9', 'A.8.8'],
    mandatory: false
  },
  {
    id: 'A.8.20',
    title: 'Network Security',
    description: 'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect networks from security threats',
    implementationGuidance: 'Implement network security controls including firewalls, intrusion detection, and network segmentation. Include network monitoring and access controls.',
    typicalEvidence: ['Network security architecture', 'Firewall configurations', 'Network monitoring logs'],
    relatedControls: ['A.8.21', 'A.8.22', 'A.8.16'],
    mandatory: true
  },
  {
    id: 'A.8.21',
    title: 'Security of Network Services',
    description: 'Security mechanisms, service levels and requirements of network services shall be identified, implemented and monitored.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure secure delivery of network services',
    implementationGuidance: 'Implement security controls for network services and monitor service levels. Include service agreements, security requirements, and performance monitoring.',
    typicalEvidence: ['Network service security requirements', 'Service level agreements', 'Service monitoring reports'],
    relatedControls: ['A.8.20', 'A.5.19', 'A.8.6'],
    mandatory: false
  },
  {
    id: 'A.8.22',
    title: 'Segregation of Networks',
    description: 'Groups of information services, users and information systems shall be segregated in the organization networks.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Isolate network segments to contain security threats',
    implementationGuidance: 'Implement network segmentation to isolate different types of systems and users. Include VLANs, firewalls, and access controls between segments.',
    typicalEvidence: ['Network segmentation design', 'VLAN configuration', 'Inter-segment access controls'],
    relatedControls: ['A.8.20', 'A.8.3', 'A.5.15'],
    mandatory: false
  },
  {
    id: 'A.8.23',
    title: 'Web Filtering',
    description: 'Access to external websites shall be managed to reduce exposure to malicious content.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Reduce security risks from web browsing',
    implementationGuidance: 'Implement web filtering and content control systems. Include URL filtering, content scanning, and malware protection for web traffic.',
    typicalEvidence: ['Web filtering system configuration', 'Filtering policies', 'Web access logs'],
    relatedControls: ['A.8.7', 'A.8.20', 'A.6.3'],
    mandatory: false
  },
  {
    id: 'A.8.24',
    title: 'Use of Cryptography',
    description: 'Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect information through appropriate cryptographic controls',
    implementationGuidance: 'Implement appropriate cryptographic controls to protect sensitive information in transit and at rest. Include key management, algorithm selection, and implementation standards.',
    typicalEvidence: ['Cryptographic policies', 'Key management procedures', 'Encryption implementation records'],
    relatedControls: ['A.5.14', 'A.8.12', 'A.5.12'],
    mandatory: false
  },
  {
    id: 'A.8.25',
    title: 'Secure Development Life Cycle',
    description: 'Rules for the secure development of software and systems shall be established and applied.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Integrate security into software development processes',
    implementationGuidance: 'Integrate security into the entire software development lifecycle. Include security requirements, design reviews, code reviews, and security testing.',
    typicalEvidence: ['Secure development procedures', 'Security review records', 'Development security training'],
    relatedControls: ['A.8.26', 'A.8.27', 'A.8.28'],
    mandatory: false
  },
  {
    id: 'A.8.26',
    title: 'Application Security Requirements',
    description: 'Information security requirements shall be identified, specified and approved when developing or acquiring applications.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Ensure applications meet security requirements',
    implementationGuidance: 'Define and implement security requirements for application development and acquisition. Include functional and non-functional security requirements.',
    typicalEvidence: ['Application security requirements', 'Requirements approval records', 'Security specifications'],
    relatedControls: ['A.8.25', 'A.8.29', 'A.5.8'],
    mandatory: false
  },
  {
    id: 'A.8.27',
    title: 'Secure Systems Architecture and Engineering Principles',
    description: 'Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Apply secure design principles to system architecture',
    implementationGuidance: 'Establish secure system architecture principles and apply them consistently. Include defense in depth, least privilege, and fail-safe design principles.',
    typicalEvidence: ['Secure architecture principles', 'Architecture review records', 'Design documentation'],
    relatedControls: ['A.8.25', 'A.8.26', 'A.8.31'],
    mandatory: false
  },
  {
    id: 'A.8.28',
    title: 'Secure Coding',
    description: 'Secure coding principles shall be applied to software development.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Prevent security vulnerabilities in application code',
    implementationGuidance: 'Integrate security controls into development lifecycle and change management processes. Include secure coding standards, code reviews, and static analysis.',
    typicalEvidence: ['Secure coding standards', 'Code review records', 'Static analysis reports'],
    relatedControls: ['A.8.25', 'A.8.29', 'A.8.4'],
    mandatory: false
  },
  {
    id: 'A.8.29',
    title: 'Security Testing in Development and Acceptance',
    description: 'Security testing processes shall be defined and implemented in the development lifecycle.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Identify and remediate security vulnerabilities before deployment',
    implementationGuidance: 'Implement security testing procedures including vulnerability assessments and penetration testing. Include automated testing tools and manual testing processes.',
    typicalEvidence: ['Security testing procedures', 'Testing results', 'Vulnerability remediation records'],
    relatedControls: ['A.8.25', 'A.8.26', 'A.8.34'],
    mandatory: false
  },
  {
    id: 'A.8.30',
    title: 'Outsourced Development',
    description: 'The organization shall direct, monitor and review the activities related to outsourced system development.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Maintain security oversight of outsourced development',
    implementationGuidance: 'Implement oversight and security requirements for outsourced development activities. Include contractual security requirements and ongoing monitoring.',
    typicalEvidence: ['Outsourcing security requirements', 'Vendor monitoring records', 'Development oversight documentation'],
    relatedControls: ['A.5.19', 'A.5.20', 'A.8.25'],
    mandatory: false
  },
  {
    id: 'A.8.31',
    title: 'Separation of Development, Test and Production Environments',
    description: 'Development, testing and production environments shall be separated and secured.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Prevent unauthorized changes to production systems',
    implementationGuidance: 'Implement proper separation and security controls for different environment types. Include access controls, data management, and change promotion procedures.',
    typicalEvidence: ['Environment separation documentation', 'Access control matrices', 'Change promotion procedures'],
    relatedControls: ['A.8.4', 'A.8.32', 'A.8.11'],
    mandatory: false
  },
  {
    id: 'A.8.32',
    title: 'Change Management',
    description: 'Changes to information processing facilities and information systems shall be subject to change management procedures.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Control and track changes to information systems',
    implementationGuidance: 'Implement formal change management procedures for all systems and applications. Include change approval, testing, and rollback procedures.',
    typicalEvidence: ['Change management procedures', 'Change approval records', 'Change implementation logs'],
    relatedControls: ['A.8.9', 'A.8.19', 'A.5.37'],
    mandatory: true
  },
  {
    id: 'A.8.33',
    title: 'Test Information',
    description: 'Test data shall be selected carefully, protected and controlled.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect sensitive information used in testing',
    implementationGuidance: 'Implement controls for test data management including data anonymization and protection. Include test data creation, usage, and disposal procedures.',
    typicalEvidence: ['Test data procedures', 'Data anonymization records', 'Test data inventory'],
    relatedControls: ['A.8.11', 'A.8.31', 'A.5.34'],
    mandatory: false
  },
  {
    id: 'A.8.34',
    title: 'Protection of information systems during audit testing',
    description: 'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.',
    category: 'Technology Controls',
    domain: 'Technology',
    objective: 'Protect systems during security testing and audits',
    implementationGuidance: 'Establish procedures to protect systems during audit and security testing activities. Include testing authorization, scope limitation, and system protection measures.',
    typicalEvidence: ['Audit testing procedures', 'Testing authorization records', 'System protection measures'],
    relatedControls: ['A.8.29', 'A.5.35', 'A.8.16'],
    mandatory: false
  }
]

export default iso27001AnnexAControls